apiVersion : apps/v1
kind: Deployment
metadata:
  name: demo1 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo 
          image: shraddhapa/demo22
          ports:
          - containerPort: 80
